import React, { useEffect, useMemo, useState } from "react";
import {
  ArrowDownCircle, ArrowUpCircle, Banknote, Building2, Car, CreditCard, Fuel,
  Home, Landmark, Loader2, Plus, RefreshCcw, Search, Settings, ShoppingBag,
  Sparkles, Trash2, Utensils, WalletCards, X
} from "lucide-react";

const CATEGORIES = [
  { key: "Shopping", icon: ShoppingBag, hint: "Clothes, home, gadgets" },
  { key: "Going outside", icon: Utensils, hint: "Restaurant, coffee, weekends" },
  { key: "Groceries", icon: ShoppingBag, hint: "Food and supermarket" },
  { key: "Fuel", icon: Fuel, hint: "Diesel, parking, road" },
  { key: "House", icon: Home, hint: "Utilities, repair, furniture" },
  { key: "Car", icon: Car, hint: "Service, insurance, parts" },
  { key: "Kids", icon: Sparkles, hint: "School, toys, activities" },
  { key: "Health", icon: Banknote, hint: "Doctor, pharmacy" },
  { key: "Travel", icon: Sparkles, hint: "Trips and tickets" },
  { key: "Other", icon: WalletCards, hint: "Everything else" }
];
const CREDIT_TYPES = ["House credit", "Car credit", "Personal credit", "Other credit"];
const currentMonth = new Date().toISOString().slice(0, 7);

function money(v, currency = "RON") { return new Intl.NumberFormat(undefined, { style: "currency", currency, maximumFractionDigits: 2 }).format(Number(v || 0)); }
function initials(n = "?") { return String(n || "?").trim().slice(0, 2).toUpperCase(); }
function txMonth(t) { return String(t.tx_date || "").slice(0, 7); }
function monthLabel(m) { const [y, mo] = m.split("-").map(Number); return new Date(y, mo - 1, 1).toLocaleDateString(undefined, { month: "long", year: "numeric" }); }
function normalizeDomain(v) { return String(v || "").trim().toLowerCase().replace(/^https?:\/\//, "").replace(/^www\./, "").split("/")[0].replace(/[^a-z0-9.-]/g, ""); }
function logoUrl(domain) { const d = normalizeDomain(domain); return d ? `https://logo.clearbit.com/${d}` : ""; }
function faviconUrl(domain) { const d = normalizeDomain(domain); return d ? `https://www.google.com/s2/favicons?domain=${d}&sz=128` : ""; }
function guessDomains(name) {
  const x = String(name || "").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, "").replace(/[^a-z0-9]/g, "");
  const map = { emag:"emag.ro", lidl:"lidl.ro", kaufland:"kaufland.ro", dedeman:"dedeman.ro", hornbach:"hornbach.ro", leroymerlin:"leroymerlin.ro", ikea:"ikea.com", auchan:"auchan.ro", carrefour:"carrefour.ro", altex:"altex.ro", flanco:"flanco.ro", megaimage:"mega-image.ro", profi:"profi.ro", omv:"omv.ro", petrom:"petrom.ro", rompetrol:"rompetrol.ro", mol:"molromania.ro", netflix:"netflix.com", spotify:"spotify.com", orange:"orange.ro", digi:"digi.ro", vodafone:"vodafone.ro", engie:"engie.ro", enel:"enel.ro", bcr:"bcr.ro", ing:"ing.ro", bt:"bancatransilvania.ro" };
  if (!x) return [];
  return [map[x] || `${x}.ro`, `${x}.com`].filter((v, i, a) => v && a.indexOf(v) === i);
}
function CatIcon({ name }) { const d = CATEGORIES.find(c => c.key === name) || CATEGORIES.at(-1); const I = d.icon; return <I size={17}/>; }
function Logo({ merchant, big=false }) {
  const [fallback, setFallback] = useState(false);
  const src = !fallback && (merchant?.logo_url || merchant?.logo_data);
  if (src) return <span className={big ? "logo big" : "logo"}><img src={src} onError={() => setFallback(true)} alt=""/></span>;
  return <span className={big ? "logo big" : "logo"}>{initials(merchant?.name)}</span>;
}

export default function App() {
  const [data, setData] = useState({ users: [], merchants: [], transactions: [], credits: [], settings: { currency: "RON", monthly_budget: 0, economy_target: 0 }});
  const [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState(""), [toast, setToast] = useState("");
  const [view, setView] = useState("dashboard"), [month, setMonth] = useState(currentMonth), [userFilter, setUserFilter] = useState("all"), [catFilter, setCatFilter] = useState("all");
  const [expenseOpen, setExpenseOpen] = useState(false), [incomeOpen, setIncomeOpen] = useState(false), [merchantOpen, setMerchantOpen] = useState(false), [creditOpen, setCreditOpen] = useState(false);
  const users = data.users || [], merchants = data.merchants || [], txs = data.transactions || [], credits = data.credits || [], currency = data.settings?.currency || "RON";

  async function api(action, payload={}, method="POST") {
    const r = await fetch("/api/data", { method, headers: { "content-type":"application/json" }, body: method === "POST" ? JSON.stringify({ action, ...payload }) : undefined });
    const j = await r.json().catch(() => ({})); if (!r.ok) throw new Error(j.error || "Request failed"); return j;
  }
  async function load() { setLoading(true); setError(""); try { setData(await api("load", {}, "GET")); } catch(e) { setError(e.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function save(promise, msg) { setSaving(true); setError(""); try { await promise; await load(); setToast(msg); setTimeout(()=>setToast(""),2500); return true; } catch(e) { setError(e.message); return false; } finally { setSaving(false); } }

  const months = useMemo(() => Array.from(new Set([currentMonth, ...txs.map(txMonth).filter(Boolean)])).sort().reverse(), [txs]);
  const monthTx = txs.filter(t => txMonth(t) === month);
  const visibleTx = monthTx.filter(t => (userFilter === "all" || t.user_id === userFilter) && (catFilter === "all" || t.category === catFilter));
  const income = monthTx.filter(t => t.type === "income").reduce((s,t)=>s+Number(t.amount),0);
  const expenses = monthTx.filter(t => t.type === "expense").reduce((s,t)=>s+Number(t.amount),0);
  const creditMonthly = credits.filter(c => c.is_active !== false).reduce((s,c)=>s+Number(c.monthly_payment||0),0);
  const remaining = income - expenses - creditMonthly;
  const budget = Number(data.settings?.monthly_budget || 0), economyTarget = Number(data.settings?.economy_target || 0);
  const budgetPct = budget ? Math.min(100, Math.round(expenses / budget * 100)) : 0;
  const ecoPct = economyTarget ? Math.min(100, Math.round(Math.max(remaining, 0) / economyTarget * 100)) : 0;
  const totalsByUser = users.map(u => { const a = monthTx.filter(t => t.user_id === u.id); return { user:u, income:a.filter(t=>t.type==="income").reduce((s,t)=>s+Number(t.amount),0), expense:a.filter(t=>t.type==="expense").reduce((s,t)=>s+Number(t.amount),0) }; });
  const catTotals = Object.entries(monthTx.filter(t=>t.type==="expense").reduce((m,t)=>({...m,[t.category]:(m[t.category]||0)+Number(t.amount)}),{})).sort((a,b)=>b[1]-a[1]);
  const merchantById = Object.fromEntries(merchants.map(m=>[m.id,m]));
  const topMerchants = Object.values(monthTx.filter(t=>t.type==="expense").reduce((m,t)=>{ const merch=merchantById[t.merchant_id]||{id:"?",name:"Unknown"}; m[merch.id]=m[merch.id]||{merchant:merch,total:0}; m[merch.id].total+=Number(t.amount); return m; },{})).sort((a,b)=>b.total-a.total).slice(0,6);

  return <div className="app">
    <aside className="side">
      <div className="brand"><div className="brandmark">AA</div><div><b>AMINE & ALINA</b><span>Home Finance</span></div></div>
      <label className="monthbox">Month<select value={month} onChange={e=>setMonth(e.target.value)}>{months.map(m=><option key={m} value={m}>{monthLabel(m)}</option>)}</select></label>
      <nav>
        <Btn active={view==="dashboard"} onClick={()=>setView("dashboard")} icon={WalletCards}>Dashboard</Btn>
        <Btn active={view==="incomes"} onClick={()=>setView("incomes")} icon={ArrowUpCircle}>Incomes</Btn>
        <Btn active={view==="expenses"} onClick={()=>setView("expenses")} icon={ArrowDownCircle}>Expenses</Btn>
        <Btn active={view==="credits"} onClick={()=>setView("credits")} icon={Building2}>Credits</Btn>
        <Btn active={view==="merchants"} onClick={()=>setView("merchants")} icon={Landmark}>Merchants</Btn>
        <Btn active={view==="settings"} onClick={()=>setView("settings")} icon={Settings}>Settings</Btn>
      </nav>
      <div className="catnav"><small>Expense categories</small><button className={catFilter==="all"?"active":""} onClick={()=>{setCatFilter("all");setView("expenses")}}>All expenses</button>{CATEGORIES.map(c=>{const I=c.icon;return <button key={c.key} className={catFilter===c.key?"active":""} onClick={()=>{setCatFilter(c.key);setView("expenses")}}><I size={16}/>{c.key}</button>})}</div>
    </aside>
    <main className="main">
      <header className="top"><div><small>{view}</small><h1>{view==="dashboard"?"What remains this month?":view[0].toUpperCase()+view.slice(1)}</h1><p>No passcode. Clean family budget with incomes, expenses, credits and economies.</p></div><div className="actions"><select value={userFilter} onChange={e=>setUserFilter(e.target.value)}><option value="all">All users</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><button className="soft" onClick={load}><RefreshCcw size={16}/>Refresh</button><button className="income" onClick={()=>setIncomeOpen(true)}><Plus size={16}/>Income</button><button className="primary" onClick={()=>setExpenseOpen(true)}><Plus size={16}/>Expense</button></div></header>
      {error && <div className="error">{error}</div>}
      {loading ? <div className="panel loading"><Loader2 className="spin"/> Loading...</div> : view === "dashboard" ? <Dashboard currency={currency} income={income} expenses={expenses} creditMonthly={creditMonthly} remaining={remaining} budget={budget} budgetPct={budgetPct} economyTarget={economyTarget} ecoPct={ecoPct} totalsByUser={totalsByUser} catTotals={catTotals} topMerchants={topMerchants} users={users} merchants={merchants} txs={visibleTx} onMonthlyIncome={(u)=>save(api("addMonthlyIncome",{userId:u.id,month}),`Income added for ${u.name}`)} onDelete={(id)=>save(api("deleteTransaction",{id}),"Transaction deleted")}/> : view === "incomes" ? <Incomes users={users} currency={currency} totalsByUser={totalsByUser} saving={saving} onIncome={()=>setIncomeOpen(true)} onAddUser={(name)=>save(api("addUser",{name}),"User added")} onUpdate={(id,monthly_income)=>save(api("updateUser",{id,monthly_income:Number(monthly_income||0)}),"Income updated")} onMonthly={(u)=>save(api("addMonthlyIncome",{userId:u.id,month}),`Income added for ${u.name}`)}/> : view === "expenses" ? <Expenses txs={visibleTx.filter(t=>t.type==="expense")} users={users} merchants={merchants} currency={currency} catFilter={catFilter} setCatFilter={setCatFilter} onAdd={()=>setExpenseOpen(true)} onDelete={(id)=>save(api("deleteTransaction",{id}),"Expense deleted")}/> : view === "credits" ? <Credits credits={credits} currency={currency} onAdd={()=>setCreditOpen(true)} onDelete={(id)=>save(api("deleteCredit",{id}),"Credit deleted")}/> : view === "merchants" ? <Merchants merchants={merchants} onAdd={()=>setMerchantOpen(true)} onDelete={(id)=>save(api("deleteMerchant",{id}),"Merchant deleted")}/> : <SettingsView settings={data.settings} saving={saving} onSave={(p)=>save(api("updateSettings",p),"Settings saved")}/>}    
    </main>
    <button className="fab" onClick={()=>setExpenseOpen(true)}><Plus/></button>
    {expenseOpen && <ExpenseModal users={users} merchants={merchants} selectedUser={userFilter} selectedCategory={catFilter} currency={currency} saving={saving} onNewMerchant={()=>setMerchantOpen(true)} onClose={()=>setExpenseOpen(false)} onAdd={(p)=>save(api("addTransaction",{...p,type:"expense"}),"Expense added").then(ok=>ok&&setExpenseOpen(false))}/>} 
    {incomeOpen && <IncomeModal users={users} merchants={merchants} currency={currency} saving={saving} onClose={()=>setIncomeOpen(false)} onAdd={(p)=>save(api("addTransaction",{...p,type:"income",category:"Income"}),"Income added").then(ok=>ok&&setIncomeOpen(false))}/>} 
    {merchantOpen && <MerchantModal saving={saving} onClose={()=>setMerchantOpen(false)} onSave={(p)=>save(api("addMerchant",p),"Merchant saved").then(ok=>ok&&setMerchantOpen(false))}/>} 
    {creditOpen && <CreditModal currency={currency} saving={saving} onClose={()=>setCreditOpen(false)} onSave={(p)=>save(api("addCredit",p),"Credit added").then(ok=>ok&&setCreditOpen(false))}/>} 
    {toast && <div className="toast">{toast}</div>}
  </div>;
}
function Btn({active,onClick,icon:Icon,children}){return <button className={active?"active":""} onClick={onClick}><Icon size={18}/>{children}</button>}
function Metric({label,value,tone,sub,icon:Icon}){return <div className={`metric ${tone||""}`}>{Icon&&<Icon size={18}/>}<span>{label}</span><b>{value}</b>{sub&&<small>{sub}</small>}</div>}
function Dashboard(p){ const max=Math.max(...p.catTotals.map(x=>x[1]),1); return <section className="dash"><div className={`hero ${p.remaining>=0?"ok":"badhero"}`}><div><span>Remaining after expenses + credits</span><h2>{money(p.remaining,p.currency)}</h2><p>{p.remaining>=0?"This is what can remain for living, savings and unexpected costs.":"You are above the monthly plan. Check going outside, shopping or credits."}</p></div><div className="heroStats"><Metric label="Income" value={money(p.income,p.currency)} tone="good"/><Metric label="Expenses" value={money(p.expenses,p.currency)} tone="bad"/><Metric label="Credits" value={money(p.creditMonthly,p.currency)} tone="bad"/></div></div><div className="metrics"><Metric icon={ArrowUpCircle} label="Total income" value={money(p.income,p.currency)} tone="good"/><Metric icon={ArrowDownCircle} label="Outcomes" value={money(p.expenses,p.currency)} tone="bad"/><Metric icon={Building2} label="Credits / month" value={money(p.creditMonthly,p.currency)} tone="bad"/><Metric icon={Sparkles} label="Economies" value={p.economyTarget?`${p.ecoPct}%`:"Set target"} sub={p.economyTarget?`${money(Math.max(p.remaining,0),p.currency)} / ${money(p.economyTarget,p.currency)}`:"Settings"}/></div><div className="grid2"><div className="panel"><h3>AMINE / ALINA</h3><div className="people">{p.totalsByUser.map(r=><div className="person" key={r.user.id}><div className="avatar">{initials(r.user.name)}</div><b>{r.user.name}</b><small>Default: {money(r.user.monthly_income,p.currency)}</small><span className="good">+ {money(r.income,p.currency)}</span><span className="bad">- {money(r.expense,p.currency)}</span><button onClick={()=>p.onMonthlyIncome(r.user)}>Add monthly income</button></div>)}</div></div><div className="panel"><h3>Budget / economies</h3><Progress label="Budget used" pct={p.budgetPct} text={p.budget?`${money(p.expenses,p.currency)} / ${money(p.budget,p.currency)}`:"Set budget in Settings"}/><Progress label="Economy target" pct={p.ecoPct} text={p.economyTarget?`${money(Math.max(p.remaining,0),p.currency)} potential savings`:"Set target in Settings"}/></div></div><div className="grid2"><div className="panel"><h3>Categories</h3>{p.catTotals.length? p.catTotals.map(([c,total])=><div className="barrow" key={c}><span><CatIcon name={c}/>{c}</span><div className="bar"><i style={{width:`${Math.max(5,total/max*100)}%`}}/></div><b>{money(total,p.currency)}</b></div>):<Empty text="No expenses yet"/>}</div><div className="panel"><h3>Top merchants</h3>{p.topMerchants.length?p.topMerchants.map(x=><div className="merchantLine" key={x.merchant.id}><Logo merchant={x.merchant}/><span>{x.merchant.name}</span><b>{money(x.total,p.currency)}</b></div>):<Empty text="No merchants yet"/>}</div></div><Transactions txs={p.txs} users={p.users} merchants={p.merchants} currency={p.currency} onDelete={p.onDelete}/></section>}
function Incomes({users,currency,totalsByUser,onIncome,onAddUser,onUpdate,onMonthly}){const [draft,setDraft]=useState({}),[name,setName]=useState("");useEffect(()=>{setDraft(Object.fromEntries(users.map(u=>[u.id,u.monthly_income||0])))},[users]);return <div className="panel"><div className="head"><h3>Incomes by user</h3><button className="income" onClick={onIncome}><Plus size={16}/>Add income</button></div><div className="people">{users.map(u=>{const t=totalsByUser.find(x=>x.user.id===u.id)||{};return <div className="person" key={u.id}><div className="avatar">{initials(u.name)}</div><b>{u.name}</b><small>This month: {money(t.income,currency)}</small><label>Default monthly income<input type="number" value={draft[u.id]??""} onChange={e=>setDraft({...draft,[u.id]:e.target.value})}/></label><button onClick={()=>onUpdate(u.id,draft[u.id])}>Save</button><button onClick={()=>onMonthly(u)}>Add this month</button></div>})}</div><div className="addrow"><input placeholder="Add user" value={name} onChange={e=>setName(e.target.value)}/><button className="soft" onClick={()=>{if(name.trim()){onAddUser(name.trim());setName("")}}}>Add user</button></div></div>}
function Expenses({txs,users,merchants,currency,catFilter,setCatFilter,onAdd,onDelete}){return <div className="panel"><div className="head"><h3>{catFilter==="all"?"All expenses":catFilter}</h3><button className="primary" onClick={onAdd}><Plus size={16}/>Add expense</button></div><div className="pills"><button className={catFilter==="all"?"active":""} onClick={()=>setCatFilter("all")}>All</button>{CATEGORIES.map(c=><button className={catFilter===c.key?"active":""} key={c.key} onClick={()=>setCatFilter(c.key)}>{c.key}</button>)}</div><Transactions txs={txs} users={users} merchants={merchants} currency={currency} onDelete={onDelete}/></div>}
function Credits({credits,currency,onAdd,onDelete}){const monthly=credits.reduce((s,c)=>s+Number(c.monthly_payment||0),0),rem=credits.reduce((s,c)=>s+Number(c.remaining_amount||0),0);return <div className="panel"><div className="head"><h3>Credits</h3><button className="primary" onClick={onAdd}><Plus size={16}/>Add credit</button></div><div className="metrics two"><Metric label="Monthly payments" value={money(monthly,currency)} tone="bad"/><Metric label="Remaining amount" value={money(rem,currency)}/></div><div className="cards">{credits.map(c=><div className="credit" key={c.id}><Building2/><b>{c.name}</b><span>{c.credit_type}</span><strong>{money(c.monthly_payment,currency)} / month</strong><small>Remaining: {money(c.remaining_amount,currency)}</small><button onClick={()=>onDelete(c.id)}><Trash2 size={16}/></button></div>)}</div></div>}
function Merchants({merchants,onAdd,onDelete}){return <div className="panel"><div className="head"><h3>Merchants and logos</h3><button className="primary" onClick={onAdd}><Search size={16}/>Find logo</button></div><div className="cards">{merchants.map(m=><div className="merchantCard" key={m.id}><Logo merchant={m} big/><b>{m.name}</b><small>{m.website_domain||"fallback"}</small><button onClick={()=>onDelete(m.id)}><Trash2 size={16}/></button></div>)}</div></div>}
function SettingsView({settings,onSave}){const [f,setF]=useState(settings||{});useEffect(()=>setF(settings||{}),[settings]);return <div className="panel"><h3>Settings</h3><div className="form"><label>Currency<select value={f.currency||"RON"} onChange={e=>setF({...f,currency:e.target.value})}><option>RON</option><option>EUR</option><option>MAD</option><option>USD</option><option>GBP</option></select></label><label>Monthly expense budget<input type="number" value={f.monthly_budget||""} onChange={e=>setF({...f,monthly_budget:e.target.value})}/></label><label>Economy target<input type="number" value={f.economy_target||""} onChange={e=>setF({...f,economy_target:e.target.value})}/></label></div><button className="primary" onClick={()=>onSave({currency:f.currency,monthly_budget:Number(f.monthly_budget||0),economy_target:Number(f.economy_target||0)})}>Save settings</button><p className="warn">Passcode removed as requested. Anyone with the Netlify URL can open this app.</p></div>}
function Transactions({txs,users,merchants,currency,onDelete}){const u=Object.fromEntries(users.map(x=>[x.id,x])),m=Object.fromEntries(merchants.map(x=>[x.id,x]));if(!txs.length)return <Empty text="No transactions"/>;return <div className="table"><table><thead><tr><th>Date</th><th>User</th><th>Merchant</th><th>Category</th><th>Type</th><th>Amount</th><th/></tr></thead><tbody>{txs.map(t=><tr key={t.id}><td>{t.tx_date}</td><td><b>{u[t.user_id]?.name||"-"}</b></td><td><span className="mcell"><Logo merchant={m[t.merchant_id]}/>{m[t.merchant_id]?.name||"Unknown"}</span></td><td><span className="cat"><CatIcon name={t.category}/>{t.category}</span></td><td><span className={`pill ${t.type}`}>{t.type}</span></td><td className={t.type==="income"?"good amount":"bad amount"}>{t.type==="income"?"+":"-"} {money(t.amount,currency)}</td><td><button onClick={()=>onDelete(t.id)}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>}
function Empty({text}){return <div className="empty">{text}</div>}
function Progress({label,pct,text}){return <div className="progress"><div><b>{label}</b><span>{pct}%</span></div><em><i style={{width:`${pct}%`}}/></em><small>{text}</small></div>}
function Modal({title,onClose,children}){return <div className="backdrop"><div className="modal"><div className="modalhead"><h2>{title}</h2><button onClick={onClose}><X/></button></div>{children}</div></div>}
function ExpenseModal({users,merchants,selectedUser,selectedCategory,currency,saving,onClose,onAdd,onNewMerchant}){const [f,setF]=useState({userId:selectedUser!=="all"?selectedUser:users[0]?.id||"",merchantId:merchants[0]?.id||"",amount:"",category:selectedCategory!=="all"?selectedCategory:"Shopping",tx_date:new Date().toISOString().slice(0,10),note:""});return <Modal title="Add expense" onClose={onClose}><form onSubmit={e=>{e.preventDefault();onAdd({...f,amount:Number(f.amount||0)})}}><Fields f={f} setF={setF} users={users} merchants={merchants} currency={currency} onNewMerchant={onNewMerchant} expense/><div className="modalactions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>Add expense</button></div></form></Modal>}
function IncomeModal({users,merchants,currency,saving,onClose,onAdd}){const salary=merchants.find(m=>m.name.toLowerCase()==="salary")||merchants[0];const [f,setF]=useState({userId:users[0]?.id||"",merchantId:salary?.id||"",amount:"",tx_date:new Date().toISOString().slice(0,10),note:"Income"});return <Modal title="Add income" onClose={onClose}><form onSubmit={e=>{e.preventDefault();onAdd({...f,amount:Number(f.amount||0)})}}><div className="form"><label>User<select value={f.userId} onChange={e=>setF({...f,userId:e.target.value})}>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Amount<input type="number" step="0.01" placeholder={`0.00 ${currency}`} value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></label><label>Source<select value={f.merchantId} onChange={e=>setF({...f,merchantId:e.target.value})}>{merchants.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Date<input type="date" value={f.tx_date} onChange={e=>setF({...f,tx_date:e.target.value})}/></label><label className="wide">Note<input value={f.note} onChange={e=>setF({...f,note:e.target.value})}/></label></div><div className="modalactions"><button type="button" onClick={onClose}>Cancel</button><button className="income" disabled={saving}>Add income</button></div></form></Modal>}
function Fields({f,setF,users,merchants,currency,onNewMerchant}){return <div className="form"><label>User<select value={f.userId} onChange={e=>setF({...f,userId:e.target.value})}>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Amount<input type="number" step="0.01" placeholder={`0.00 ${currency}`} value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></label><label>Merchant<div className="inline"><select value={f.merchantId} onChange={e=>setF({...f,merchantId:e.target.value})}>{merchants.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><button type="button" onClick={onNewMerchant}>Logo</button></div></label><label>Category<select value={f.category} onChange={e=>setF({...f,category:e.target.value})}>{CATEGORIES.map(c=><option key={c.key}>{c.key}</option>)}</select></label><label>Date<input type="date" value={f.tx_date} onChange={e=>setF({...f,tx_date:e.target.value})}/></label><label>Note<input value={f.note} onChange={e=>setF({...f,note:e.target.value})}/></label></div>}
function MerchantModal({saving,onClose,onSave}){const [name,setName]=useState(""),[domain,setDomain]=useState("");const suggestions=domain?[normalizeDomain(domain)]:guessDomains(name);const chosen=normalizeDomain(domain||suggestions[0]);return <Modal title="Find merchant logo" onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave({name,website_domain:chosen,logo_url:logoUrl(chosen)})}}><div className="form"><label>Merchant name<input value={name} onChange={e=>setName(e.target.value)} placeholder="eMAG, Lidl, Kaufland"/></label><label>Domain if you know it<input value={domain} onChange={e=>setDomain(e.target.value)} placeholder="emag.ro"/></label></div><div className="logobox"><Logo merchant={{name,logo_url:logoUrl(chosen)}} big/><div><b>Logo suggestions</b><div className="suggestions">{suggestions.map(d=><button type="button" key={d} onClick={()=>setDomain(d)}><img src={logoUrl(d)} onError={e=>e.currentTarget.src=faviconUrl(d)} />{d}</button>)}</div></div></div><div className="modalactions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>Save merchant</button></div></form></Modal>}
function CreditModal({currency,saving,onClose,onSave}){const [f,setF]=useState({name:"",credit_type:"House credit",monthly_payment:"",remaining_amount:"",interest_rate:"",end_date:"",note:""});return <Modal title="Add credit" onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave({...f,monthly_payment:Number(f.monthly_payment||0),remaining_amount:Number(f.remaining_amount||0),interest_rate:f.interest_rate?Number(f.interest_rate):null})}}><div className="form"><label>Name<input value={f.name} onChange={e=>setF({...f,name:e.target.value})} placeholder="House credit BCR"/></label><label>Type<select value={f.credit_type} onChange={e=>setF({...f,credit_type:e.target.value})}>{CREDIT_TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label>Monthly payment<input type="number" step="0.01" placeholder={`0.00 ${currency}`} value={f.monthly_payment} onChange={e=>setF({...f,monthly_payment:e.target.value})}/></label><label>Remaining amount<input type="number" step="0.01" value={f.remaining_amount} onChange={e=>setF({...f,remaining_amount:e.target.value})}/></label><label>Interest %<input type="number" step="0.01" value={f.interest_rate} onChange={e=>setF({...f,interest_rate:e.target.value})}/></label><label>End date<input type="date" value={f.end_date} onChange={e=>setF({...f,end_date:e.target.value})}/></label></div><div className="modalactions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>Save credit</button></div></form></Modal>}
